[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

[profile.default.optimizer]
enabled = true
runs = 200

[rpc_endpoints]
sepolia = "${ETH_RPC_URL_SEPOLIA}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
aurora_sepolia = "${AURORA_SEPOLIA_RPC_URL}"
polygon_zkevm = "${POLYGON_ZKEVM_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
avalanche_fuji = { key = "${SNOWTRACE_API_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }
